#ifndef __QUARK_RISCV64_SBI_VALUES__
#define __QUARK_RISCV64_SBI_VALUES__

namespace QUARK::sbi {

enum {
  SBI_SUCCESS = 0,
  SBI_ERR_FAILED = -1,
  SBI_ERR_NOT_SUPPORTED = -2,
  SBI_ERR_INVALID_PARAM = -3,
  SBI_ERR_DENIED = -4,
  SBI_ERR_INVALID_ADDRESS = -5,
  SBI_ERR_ALREADY_AVAILABLE = -6,
  SBI_ERR_ALREADY_STARTED = -7,
  SBI_ERR_ALREADY_STOPPED = -8,
  SBI_ERR_NO_SHMEM = -9,
  SBI_ERR_INVALID_STATE = -10,
  SBI_ERR_BAD_RANGE = -11,
  SBI_ERR_TIMEOUT = -12,
};

}

#endif
