#pragma once

namespace QUARK::ABI {

enum class Function {
    ABI_HEAP_NEW,
    ABI_HEAP_DELETE,

    ABI_THREAD_CONSTRUCTOR,
    ABI_THREAD_DESTRUCTOR,
    ABI_THREAD_JOIN,
    ABI_THREAD_EXIT,

    ABI_SEMAPHORE_CONSTRUCTOR,
    ABI_SEMAPHORE_DESTRUCTOR,
    ABI_SEMAPHORE_P,
    ABI_SEMAPHORE_V,
};

} // namespace QUARK::ABI
